1. 导入numpy库并简写为 np (★☆☆)  
>提示: import … as …  

In [11]:
import numpy as np

2. 打印numpy的版本和配置说明 (★☆☆)  
> 提示: np.__version__, np.show_config

In [12]:
print(np.__version__)
np.show_config()

1.15.0
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib'

3. 创建一个长度为10的空向量 (★☆☆)
> 提示: `np.zeros`, return the array all contains zero.

In [13]:
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4. 如何找到任何一个数组的内存大小？ (★☆☆)
> 提示: 
>   * size : the number of the elements in the array
>   * itemsize : the bytes length of the array element

In [15]:
vector = np.zeros((10, 10))
print('size: %d bytes' % (vector.size * vector.itemsize))

size: 800 bytes


5. 如何从命令行得到numpy中add函数的说明文档? (★☆☆)
> 提示: `np.info()`, used to get help information of a func, class or module

In [16]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

6. 创建一个长度为10并且除了第五个值为1的空向量 (★☆☆)

In [17]:
empty_vector = np.zeros(10)
# 第5个设置为1
empty_vector[4] = 1 
print(empty_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. 创建一个值域范围从10到49的向量(★☆☆)
> 提示: `np.arange`

In [18]:
V = np.arange(10, 49)
print(V)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


8. 反转一个向量(第一个元素变为最后一个) (★☆☆)

In [20]:
reversed_v = V[::-1]
print(reversed_v)

[[6 7 8]
 [3 4 5]
 [0 1 2]]


9. 创建一个 3x3 并且值从0到8的矩阵(★☆☆)
> 1. first generate an array contains 0 to 8
> 2. use `resharp` function

In [21]:
V = np.arange(9).reshape(3, 3)
print(V)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引 (★☆☆)
> the `np.nonzero` function return the index of the non zero element in the array

In [22]:
non_zero = np.nonzero([1,2,0,0,4,0])
print(non_zero)

(array([0, 1, 4], dtype=int64),)


11. 创建一个 3x3 的单位矩阵 (★☆☆)
> A 3x3 identity matrix
> ```
[[ 1, 0, 0],
 [ 0, 1, 0],
 [ 0, 0, 1]]
```

In [23]:
v = np.eye(3)
print(v)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


12. 创建一个 3x3x3的随机数组 (★☆☆)

In [24]:
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.69527823 0.54406217 0.78052495]
  [0.76438433 0.61356333 0.53083581]
  [0.32780734 0.59992008 0.28161533]]

 [[0.88297645 0.56797952 0.8287094 ]
  [0.12100108 0.59571658 0.32842488]
  [0.56567317 0.8032372  0.75542491]]

 [[0.91978893 0.87813913 0.31171182]
  [0.55448911 0.96042244 0.1280193 ]
  [0.61031317 0.15179371 0.71694574]]]


13. 创建一个 10x10 的随机数组并找到它的最大值和最小值 (★☆☆)

In [25]:
v = np.random.random((10, 10))
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9908437896764789 4.43843383386433e-05


14. 创建一个长度为30的随机向量并找到它的平均值 (★☆☆)

In [26]:
v = np.random.random(30)
avg = v.mean()
print(avg)

0.5600362919069206


15. 创建一个二维数组，其中边界值为1，其余值为0 (★☆☆)

v[1:-1, 1:-1]:横坐标从1到-1，纵坐标从1到-1

In [27]:
v = np.ones((3, 3))
v[1:-1, 1:-1] = 0
print(v)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


16. 对于一个存在在数组，如何添加一个用0填充的边界? (★☆☆)

In [28]:
v = np.ones((6, 6))
v = np.pad(v, 1, 'constant', constant_values=0)
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


函数 ndarray = numpy.pad(array, pad_width, mode, **kwargs)

In [29]:
v = np.ones((6, 6))
v = np.pad(v, (1, 1), 'constant', constant_values=(0, 0))
# (1,1)表示在一维数组array前面填充1位，最后面填充1位
#  constant_values=(0,0) 表示前面填充0，后面填充0
print(v)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


17. 以下表达式运行的结果分别是什么? (★☆☆)

In [30]:
print(0*np.nan)

nan


In [31]:
print(np.nan == np.nan)

False


In [32]:
print(np.inf > np.nan)
# numpy中的inf表示一个无限大的正数

False


In [33]:
print(np.nan - np.nan)

nan


In [34]:
print(0.3 == 3 * 0.1)

False


    0.3 对应的二进制数为 0.01001100110011001 ……无限循环下去。
    而电脑会把这个无限循环的东西截断为：0.0100110011001100110011001100110011001100110011001101
    这个截断以后的二进制再转换回十进制，就变成了 0.30000000000000004

In [35]:
print( 3 * 0.1)

0.30000000000000004


18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置 (★☆☆)
> 1. generate a 1-d array [1,2,3,4]
> 2. use `np.diag` to create 2-d array

当 np.diag(array) 中

array是一个1维数组时，结果形成一个以一维数组为对角线元素的矩阵，
>numpy.diag(array,1)输出：以array为对角线上一行的二维数组，
>numpy.diag(array,-1)输出：以array为对角线下一行的二维数组

array是一个二维矩阵时，结果输出矩阵的对角线元素，
>numpy.diag(array,1)输出为对角线上一行的值
>numpy.diag(array,-1)输出为对角线下一行的值

In [39]:
v = np.diag(1 + np.arange(4), k=-1)
print(v)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


19. 创建一个8x8 的矩阵，并且设置成棋盘样式 (★☆☆)

In [37]:
v = np.zeros((8,8), dtype=int)
v[1::2, ::2] = 1
v[::2, 1::2] = 1
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [30]:
print(np.unravel_index(100, (6, 7, 8)))

(1, 5, 4)


21. 用tile函数去创建一个 8x8的棋盘样式矩阵(★☆☆)

In [31]:
v = np.tile(np.array([[0,1], [1,0]]), (4,4))
print(v)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


22. 对一个5x5的随机矩阵做归一化(★☆☆)
> 这里有两种归一化处理，一种全局最大最小值，另外一种按照每一列分别最大最小值  
> 应该第二种的归一特征应该不会影响其他列

In [10]:
v = np.random.random((6, 6))
print(v)
# way 1
v_max, v_min = v.max(), v.min()
r1 = (v - v_min)/(v_max - v_min)
print(r1)

# way 2
v_max0, v_min0 = v.max(0), v.min(0)
ranges = v_max0 - v_min0

m = v.shape[0]
diff_norm_data = v - np.tile(v_min0, (m,1))
norm_data_set1 = diff_norm_data / np.tile(ranges, (m,1))

print(norm_data_set1)

[[0.69003137 0.25532621 0.1118968  0.49330403 0.21227023 0.69866622]
 [0.00558337 0.73072196 0.24924803 0.92645812 0.20761539 0.18630234]
 [0.42172896 0.29731241 0.50182232 0.73573726 0.23043208 0.88308831]
 [0.84604681 0.89905369 0.30797273 0.49450212 0.77100012 0.2075642 ]
 [0.93170149 0.80182943 0.81867467 0.09948778 0.9266351  0.06419136]
 [0.66467386 0.63295166 0.76856678 0.06317588 0.10121101 0.42896614]]
[[0.73905044 0.26966629 0.11479468 0.526629   0.22317549 0.74837414]
 [0.         0.78298715 0.26310322 0.99433834 0.2181493  0.19513598]
 [0.44934397 0.31500198 0.53582684 0.78840255 0.24278621 0.94750866]
 [0.90751214 0.9647477  0.32651273 0.52792267 0.82647854 0.21809403]
 [1.         0.85976728 0.87795637 0.10139572 0.99452943 0.06328349]
 [0.71167001 0.67741714 0.82385108 0.062187   0.10325642 0.4571585 ]]
[[0.73905044 0.         0.         0.49824742 0.13454807 0.77479207]
 [0.         0.73850466 0.19433436 1.         0.12890874 0.14911641]
 [0.44934397 0.06522357 0.551694

23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？(★☆☆)

In [2]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？ (★☆☆)

In [3]:
v = np.dot(np.ones((5,3)), np.ones((3,2)))
print(v)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


25. 给定一个一维数组，对其在3到8之间的所有元素取反 (★☆☆)

In [5]:
v = np.arange(10)
v[(3<=v)&(v<=8)] *= -1
print(v)

[ 0  1  2 -3 -4 -5 -6 -7 -8  9]


26. 下面脚本运行后的结果是什么? (★☆☆)
> 为啥前后结果不一样

In [6]:
print(sum(range(5), -1))

9


In [7]:
from numpy import *
print(sum(range(5), -1))

10


27. 考虑一个整数向量Z,下列表达合法的是哪个? (★☆☆)

In [8]:
v = np.arange(5)
v ** v

array([  1,   1,   4,  27, 256])

In [7]:
v = np.arange(5)
2 << v >> 2

array([0, 1, 2, 4, 8])

In [3]:
v = np.arange(5)
v <- v

array([False, False, False, False, False])

In [4]:
v = np.arange(5)
1j*v

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [5]:
v = np.arange(5)
v/1/1

array([0., 1., 2., 3., 4.])

In [6]:
v = np.arange(5)
v<v>v

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. 下列表达式的结果分别是什么?(★☆☆)

In [8]:
print(np.array(0) / np.array(0))

nan


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [9]:
print(np.array(0) // np.array(0))

0


/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [10]:
print(np.array([np.nan]).astype(int).astype(float))

[-9.22337204e+18]


29. 如何从零位对浮点数组做舍入 ? (★☆☆)

In [11]:
v = np.random.uniform(-10, +10, 10)
print(np.copysign(np.ceil(np.abs(v)), v))

[-5.  4. -2. -9.  6. -4. -9.  1.  6.  1.]


30. 如何找到两个数组中的共同元素? (★☆☆)

In [12]:
v1 = np.random.randint(0, 10, 10)
v2 = np.random.randint(0, 10, 10)
print(np.intersect1d(v1, v2))

[0 3 7]


31. 如何忽略所有的 numpy 警告(尽管不建议这么做)? (★☆☆)

In [14]:
defaults = np.seterr(all='ignore')
v = np.ones(1) / 0

_ = np.seterr(**defaults)

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. 下面的表达式是正确的吗? (★☆☆)

In [15]:
np.sqrt(-1) == np.emath.sqrt(-1)

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

33. 如何得到昨天，今天，明天的日期? (★☆☆)

In [16]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print('Yesterday is ', yesterday)
print('Today is ', today)
print('Tomorrow is ', tomorrow)


Yesterday is  2019-06-20
Today is  2019-06-21
Tomorrow is  2019-06-22


34. 如何得到所有与2016年7月对应的日期？ (★★☆)

In [18]:
v = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(v)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)? (★★☆)

In [19]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A, B, out=B)
np.divide(A,2,out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([-1.5, -1.5, -1.5])

36. 用五种不同的方法去提取一个随机数组的整数部分(★★☆)

In [21]:
v = np.random.uniform(0, 10, 10)
print(v)
print(v - v%1)
print(np.floor(v))
print(v.astype(int))
print(np.ceil(v) - 1)
print(np.trunc(v))

[3.68704895 2.64349566 6.8672185  8.61802741 9.96122828 0.24174461
 5.72547933 7.28264261 7.93621915 9.36758942]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]
[3 2 6 8 9 0 5 7 7 9]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]
[3. 2. 6. 8. 9. 0. 5. 7. 7. 9.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)

In [22]:
v = np.zeros((5,5))
v += np.arange(5)
print(v)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)

In [2]:
def generate():
    for x in range(10):
        yield x

v = np.fromiter(generate(), dtype=float, count=-1)
print(v)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)

In [3]:
v = np.linspace(0, 1, 11, endpoint=False)[1:]
print(v)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


40. 创建一个长度为10的随机向量，并将其排序 (★★☆)

In [4]:
v = np.random.random(10)
print(v)
v.sort()
print(v)

[0.88735466 0.67448082 0.70716609 0.15003484 0.21767853 0.37902043
 0.87191868 0.59519264 0.40722987 0.78681261]
[0.15003484 0.21767853 0.37902043 0.40722987 0.59519264 0.67448082
 0.70716609 0.78681261 0.87191868 0.88735466]


41.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)

In [5]:
v = np.arange(10)
np.add.reduce(v)

45

42. 对于两个随机数组A和B，检查它们是否相等(★★☆)

In [6]:
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
e1 = np.array_equal(a, b)
print(e1)
e2 = np.allclose(a,b)
print(e2)

False
False


43. 创建一个只读数组(read-only) (★★☆)

In [8]:
v = np.zeros(10)
v.flags.writeable = False
v[0] = 1

ValueError: assignment destination is read-only

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)

In [11]:
v = np.random.random((10,2))
x,y = v[:,0], v[:,1]
# 距离
r = np.sqrt(x**2, y**2)
# 角度
t = np.arctan2(y,x)
print(r)
print(t)

[0.39676937 0.43422024 0.94488514 0.37967117 0.20801399 0.3383388
 0.76177745 0.9213726  0.07867197 0.79865613]
[1.05435359 0.78832439 0.51466034 1.11865018 0.20219041 1.12636779
 0.75289351 0.47756715 1.40597893 0.72079018]


45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)

In [4]:
v = np.random.random(10)
# 这里为啥是0 而不是1???
v[v.argmax()] = 0
print(v)

[0.62616625 0.95798708 0.78213085 0.07857785 0.32968123 0.18956389
 0.39396523 0.83297597 0.49246132 1.        ]


46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)

In [5]:
v = np.zeros((5,5), [('x',float),('y',float)])
v['x'], v['y'] = np.meshgrid(np.linspace(0,1,5), np.linspace(0,1,5))
print(v)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

48. 打印每个numpy标量类型的最小值和最大值？ (★★☆)

In [6]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)

for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何打印一个数组中的所有数值? (★★☆)

In [10]:
np.set_printoptions(threshold=np.NAN)
v = np.zeros((16,16))
print(v)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

50. 给定标量时，如何找到数组中最接近标量的值？(★★☆)

In [11]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print (Z[index])

53


51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组(★★☆

In [12]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1), ('y', float, 1)]), ('color',    [ ('r', float, 1), ('g', float, 1), ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


52. 对一个表示坐标形状为(100,2)的随机向量，找到点与点的距离(★★☆)

In [14]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)
# 方法2
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial
D = scipy.spatial.distance.cdist(Z,Z)
print (D)

[[0.         0.76243015 0.1049765  0.41898018 0.45935741 0.4696499
  0.77208609 0.16967405 0.34426003 0.18272032]
 [0.76243015 0.         0.66230625 0.50168205 0.8512345  0.92747041
  0.41023907 0.90045308 0.43167256 0.82921444]
 [0.1049765  0.66230625 0.         0.32359336 0.43150817 0.51654752
  0.70507813 0.26950918 0.23970042 0.25379556]
 [0.41898018 0.50168205 0.32359336 0.         0.3501133  0.81338678
  0.73295063 0.58861968 0.18500182 0.5753984 ]
 [0.45935741 0.8512345  0.43150817 0.3501133  0.         0.92898022
  1.05452259 0.59108625 0.48390101 0.64023581]
 [0.4696499  0.92747041 0.51654752 0.81338678 0.92898022 0.
  0.70356209 0.37291393 0.65716529 0.29189272]
 [0.77208609 0.41023907 0.70507813 0.73295063 1.05452259 0.70356209
  0.         0.84497402 0.57086245 0.74331496]
 [0.16967405 0.90045308 0.26950918 0.58861968 0.59108625 0.37291393
  0.84497402 0.         0.50128325 0.10875698]
 [0.34426003 0.43167256 0.23970042 0.18500182 0.48390101 0.65716529
  0.57086245 0.501283

53. 如何将32位的浮点数(float)转换为对应的整数(integer)?

In [15]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


54. 如何读取以下文件? (★★☆)

In [69]:
from io import StringIO
text = StringIO('1,2,3,4,5,6,7,8,9,10,11')
# v = np.genfromtxt(text,dtype=[('myint','i8'),('myfloat','f8'), ('mystring','S5')], delimiter=",")
v = np.genfromtxt(text, delimiter=",")
print(v)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


55. 对于numpy数组，enumerate的等价操作是什么？(★★☆)

In [16]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


56. 生成一个通用的二维Gaussian-like数组 (★★☆)

In [17]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

57. 对一个二维数组，如何在其内部随机放置p个元素? (★★☆)

In [18]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


58. 减去一个矩阵中的每一行的平均值 (★★☆)

In [19]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


[[-0.05891605  0.20550184 -0.1509368   0.10997857 -0.07737432 -0.31072899
  -0.2016621  -0.21647091  0.42246539  0.27814336]
 [-0.24717333 -0.06385028  0.22487592 -0.00591425 -0.00284555  0.24743162
  -0.05181425  0.22177925 -0.12252374 -0.19996539]
 [-0.38830101 -0.11321673 -0.12186872  0.06954556  0.22239959  0.32148208
   0.2912984   0.45647657 -0.31386627 -0.42394948]
 [ 0.47459229  0.43596921 -0.36156688 -0.00086712  0.24931799 -0.33378722
   0.37940188 -0.48756776  0.09252682 -0.44801919]
 [-0.28029512  0.46496743 -0.29564622  0.46279561 -0.35269481 -0.0771259
  -0.37962285  0.36768819  0.12131079 -0.03137713]]


59. 如何通过第n列对一个数组进行排序? (★★☆)

In [20]:
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[7 6 1]
 [9 0 9]
 [2 6 5]]
[[9 0 9]
 [7 6 1]
 [2 6 5]]


60. 如何检查一个二维数组是否有空列？(★★☆)

In [21]:
Z = np.random.randint(0,3,(3,10))
print ((~Z.any(axis=0)).any())

True


61. 从数组中的给定值中找出最近的值 (★★☆)

In [22]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5120823917193186


62. 如何用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组? (★★☆)

In [23]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


63. 创建一个具有name属性的数组类(★★☆)

In [24]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


64. 考虑一个给定的向量，如何对由第二个向量索引的每个元素加1(小心重复的索引)? (★★★)

In [25]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[5. 3. 3. 3. 3. 3. 2. 1. 3. 4.]


65. 根据索引列表(I)，如何将向量(X)的元素累加到数组(F)? (★★★)

In [26]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量(★★★)
(提示: np.unique)

In [27]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)

8


67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？ (★★★)

In [28]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print (sum)

[[79 47 58 63]
 [39 56 43 61]
 [49 50 58 67]]


68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？(★★★)

In [29]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)

[0.41217617 0.49520359 0.58620406 0.46404849 0.54535986 0.68207334
 0.55968044 0.40475367 0.44780491 0.60594043]


69. 如何获得点积 dot prodcut的对角线? (★★★)

In [31]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.sum(A * B.T, axis=1)

array([0.86561617, 1.2675724 , 1.07437344, 1.10038431, 1.76458293])

70. 考虑一个向量[1,2,3,4,5],如何建立一个新的向量，在这个新向量中每个值之间有3个连续的零？(★★★)

In [32]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？(★★★)

In [33]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print (A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


72. 如何对一个数组中任意两行做交换? (★★★)

In [34]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

In [35]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)

[(14, 27) (14, 34) (16, 49) (16, 62) (18, 45) (18, 49) (18, 77) (18, 89)
 (20, 25) (20, 39) (25, 39) (27, 34) (33, 61) (33, 85) (40, 60) (40, 84)
 (43, 81) (43, 97) (45, 49) (49, 62) (60, 84) (61, 73) (61, 84) (61, 85)
 (61, 97) (61, 98) (73, 97) (77, 89) (81, 97) (84, 98)]


74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C(★★★)

In [36]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)

[1 1 2 3 4 4 6]


75. 如何通过滑动窗口计算一个数组的平均数? (★★★)

In [37]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)

print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [38]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？(★★★)

In [40]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.34547638, -0.19343138,  0.34582313, -0.52595517, -0.96973804,
        0.36161465,  0.6482063 , -0.56448527, -0.65842704, -0.55537213,
        0.6068488 , -0.52198968, -0.02360468, -0.56195176,  0.37326362,
       -0.81394506,  0.40334512,  0.49488626,  0.59363081, -0.38778696,
       -0.11822527, -0.88497466,  0.01656397, -0.68575479,  0.53636333,
       -0.47709405, -0.1045347 , -0.84855524, -0.97907979, -0.72867154,
       -0.58898519, -0.0960375 , -0.33101904,  0.60627298, -0.78173931,
        0.25778582,  0.57517854,  0.99017523,  0.84158648, -0.15879225,
        0.16653446,  0.89429305, -0.56055358, -0.72764848, -0.01610181,
        0.97354483, -0.57392592,  0.98210758, -0.75262022, -0.52902491,
       -0.95903934, -0.31806514,  0.15331403, -0.22280156,  0.5947461 ,
       -0.24394847,  0.09341142,  0.55082343,  0.31484279,  0.50999944,
       -0.92014507,  0.95937513, -0.97682665,  0.05404803,  0.29692286,
       -0.35195547,  0.53727296, -0.34993856,  0.03033192,  0.56

78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？(★★★)

In [41]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))

print (distance(P0, P1, p))

[ 4.1841481   4.69971662  7.64776507  5.10871526 15.00353657 12.11828708
  1.31686632  7.15252115  6.35247377 12.9310685 ]


79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？(★★★)

In [42]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 3.34334201 14.73715934  1.5557994  11.77109599  6.60524298 12.84962037
   4.10036214  2.56633862  9.31135055  1.46636209]
 [ 7.43248138  2.85985075  4.7669199   0.05535016  2.73563517  0.5244331
   6.59092089  9.16044981  3.08811956  5.41638054]
 [ 6.98863216 17.05466476  3.94911363  9.95618496 11.27948258 14.04695001
   1.07467537  5.12585833  9.38167715  4.95239784]
 [14.21415619  3.32626147  2.95266254  2.93845141  9.76201494  4.97970694
   8.28497541 15.47385417  7.76578099 11.75446244]
 [ 4.93484353  6.59539985  1.11567401  6.10986187  1.44569702  5.09865938
   0.2744576   5.62906517  2.16910462  7.43787298]
 [ 2.2431496   7.58276115  6.20327599  2.30985352  2.65047169  4.71749864
   5.33641974  4.3382927   0.46527708  0.53451092]
 [13.58182959  2.72847814  3.02748087  2.58799064  9.12556312  4.42981516
   8.04503704 14.8678176   7.27873023 11.22622809]
 [ 9.03417681  1.25435393  4.98782414  1.14262253  4.26646838  1.02803456
   7.55534087 10.7711237   4.54327153  6.48151026]
 

80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)

In [43]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)

[[1 7 6 1 4 3 1 5 9 0]
 [0 8 8 8 9 5 9 7 5 4]
 [7 3 1 8 1 0 1 1 2 3]
 [1 2 5 0 6 8 3 2 8 8]
 [5 8 3 6 8 2 0 6 0 2]
 [3 6 9 3 6 5 4 7 7 3]
 [5 8 5 7 7 1 0 9 1 5]
 [3 4 8 8 7 4 7 5 0 6]
 [0 4 2 4 8 9 7 6 2 2]
 [8 5 8 4 1 4 3 8 6 5]]
[[0 0 0 0 0]
 [0 1 7 6 1]
 [0 0 8 8 8]
 [0 7 3 1 8]
 [0 1 2 5 0]]


c:\users\chinshan\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? (★★★)

In [44]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. 计算一个矩阵的秩(★★★)

In [45]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)

10


83. 如何找到一个数组中出现频率最高的值？

In [46]:
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())

0


84. 从一个10x10的矩阵中提取出连续的3x3区块(★★★)

In [47]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print (C)

[[[[1 1 4]
   [4 2 0]
   [3 0 4]]

  [[1 4 0]
   [2 0 3]
   [0 4 3]]

  [[4 0 1]
   [0 3 1]
   [4 3 0]]

  [[0 1 1]
   [3 1 0]
   [3 0 3]]

  [[1 1 3]
   [1 0 3]
   [0 3 0]]

  [[1 3 4]
   [0 3 4]
   [3 0 2]]

  [[3 4 1]
   [3 4 0]
   [0 2 2]]

  [[4 1 1]
   [4 0 1]
   [2 2 4]]]


 [[[4 2 0]
   [3 0 4]
   [4 3 3]]

  [[2 0 3]
   [0 4 3]
   [3 3 1]]

  [[0 3 1]
   [4 3 0]
   [3 1 1]]

  [[3 1 0]
   [3 0 3]
   [1 1 4]]

  [[1 0 3]
   [0 3 0]
   [1 4 2]]

  [[0 3 4]
   [3 0 2]
   [4 2 3]]

  [[3 4 0]
   [0 2 2]
   [2 3 2]]

  [[4 0 1]
   [2 2 4]
   [3 2 3]]]


 [[[3 0 4]
   [4 3 3]
   [0 3 0]]

  [[0 4 3]
   [3 3 1]
   [3 0 2]]

  [[4 3 0]
   [3 1 1]
   [0 2 0]]

  [[3 0 3]
   [1 1 4]
   [2 0 3]]

  [[0 3 0]
   [1 4 2]
   [0 3 4]]

  [[3 0 2]
   [4 2 3]
   [3 4 4]]

  [[0 2 2]
   [2 3 2]
   [4 4 2]]

  [[2 2 4]
   [3 2 3]
   [4 2 2]]]


 [[[4 3 3]
   [0 3 0]
   [1 2 1]]

  [[3 3 1]
   [3 0 2]
   [2 1 3]]

  [[3 1 1]
   [0 2 0]
   [1 3 1]]

  [[1 1 4]
   [2 0 3]
   [3 1 4]]

  [[1 4 2]
   

85. 创建一个满足 Z[i,j] == Z[j,i]的子类 (★★★)

In [48]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)

[[ 6 10 11  9  4]
 [10  1 13  9  2]
 [11 13  3 42  8]
 [ 9  9 42  5  8]
 [ 4  2  8  8  9]]


86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？(★★★)

In [49]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? (★★★)

In [50]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print (S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88. 如何利用numpy数组实现Game of Life? (★★★)

In [51]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


89. 如何找到一个数组的第n个最大值? (★★★)

In [52]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

[9995 9996 9997 9998 9999]


90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)(★★★)

In [53]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


91. 如何从一个正常数组创建记录数组(record array)? (★★★)

In [54]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats = 'S8, f8, i8')
print (R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


92. 考虑一个大向量Z, 用三种不同的方法计算它的立方(★★★)

In [55]:
x = np.random.rand()
np.power(x,3)

0.9887340153040709

93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？ (★★★)

In [56]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)

[1 3 6 7]


94. 考虑一个10x3的矩阵，分解出有不全相同值的行 (如 [2,2,3]) (★★★)

In [57]:
Z = np.random.randint(0,5,(10,3))
print (Z)

# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)

[[1 4 4]
 [4 4 3]
 [1 1 2]
 [1 1 1]
 [3 1 1]
 [1 3 4]
 [1 2 4]
 [0 4 4]
 [1 0 4]
 [0 4 1]]
[[1 4 4]
 [4 4 3]
 [1 1 2]
 [3 1 1]
 [1 3 4]
 [1 2 4]
 [0 4 4]
 [1 0 4]
 [0 4 1]]


95. 将一个整数向量转换为matrix binary的表现形式 (★★★)

In [59]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


96. 给定一个二维数组，如何提取出唯一的(unique)行?(★★★)

In [60]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)

[[0 0 0]
 [0 1 0]
 [0 1 1]]


97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数(★★★)

In [61]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)1
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

sum
6.0788487237683135
A * B
[0.14087966 0.06678032 0.73855308 0.56946124 0.34333455 0.17749726
 0.35680843 0.00582251 0.49958578 0.66360743]
inner
3.5623302524210034
outer
[[0.14087966 0.01819158 0.17904054 0.20690712 0.10318521 0.05460961
  0.17018013 0.00372837 0.20585262 0.19663148]
 [0.51716181 0.06678032 0.65724836 0.75954513 0.37878747 0.200469
  0.62472229 0.01368665 0.75567409 0.72182377]
 [0.58113716 0.07504136 0.73855308 0.85350445 0.42564527 0.22526796
  0.70200338 0.01537975 0.84915454 0.81111677]
 [0.38773681 0.05006787 0.49276527 0.56946124 0.28399206 0.15029959
  0.46837918 0.01026142 0.56655896 0.54118003]
 [0.46875762 0.06052996 0.59573265 0.68845488 0.34333455 0.18170594
  0.56625089 0.01240563 0.68494615 0.65426408]
 [0.45790024 0.05912796 0.58193427 0.67250886 0.33538222 0.17749726
  0.55313537 0.01211829 0.6690814  0.63910999]
 [0.29537556 0.0381414  0.37538561 0.43381213 0.21634343 0.11449732
  0.35680843 0.00781709 0.4316012  0.41226768]
 [0.22000856 0.02840937 

98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)? (★★★)

In [62]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [64]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0], [2.0, 0.0, 1.0, 1.0], [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])

[[2. 0. 1. 1.]]


100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。

In [65]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)


[-0.0998764   0.29606429]
